// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/settlement/settlement.proto

package settlementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReconcileBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileBatchRequest) Reset() {
	*x = ReconcileBatchRequest{}
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileBatchRequest) ProtoMessage() {}

func (x *ReconcileBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileBatchRequest.ProtoReflect.Descriptor instead.
func (*ReconcileBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_settlement_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *ReconcileBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type ReconcileBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileBatchResponse) Reset() {
	*x = ReconcileBatchResponse{}
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileBatchResponse) ProtoMessage() {}

func (x *ReconcileBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileBatchResponse.ProtoReflect.Descriptor instead.
func (*ReconcileBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_settlement_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *ReconcileBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReconcileBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetBatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchStatusRequest) Reset() {
	*x = GetBatchStatusRequest{}
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchStatusRequest) ProtoMessage() {}

func (x *GetBatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_settlement_settlement_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchStatusRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetBatchStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatchId              string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	BatchDate            string                 `protobuf:"bytes,2,opt,name=batch_date,json=batchDate,proto3" json:"batch_date,omitempty"`                                  // YYYY-MM-DD
	BatchStatus          string                 `protobuf:"bytes,3,opt,name=batch_status,json=batchStatus,proto3" json:"batch_status,omitempty"`                            // OPEN / READY
	ReconciliationStatus string                 `protobuf:"bytes,4,opt,name=reconciliation_status,json=reconciliationStatus,proto3" json:"reconciliation_status,omitempty"` // RECONCILED / FAILED
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetBatchStatusResponse) Reset() {
	*x = GetBatchStatusResponse{}
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchStatusResponse) ProtoMessage() {}

func (x *GetBatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_settlement_settlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_settlement_settlement_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatchStatusResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *GetBatchStatusResponse) GetBatchDate() string {
	if x != nil {
		return x.BatchDate
	}
	return ""
}

func (x *GetBatchStatusResponse) GetBatchStatus() string {
	if x != nil {
		return x.BatchStatus
	}
	return ""
}

func (x *GetBatchStatusResponse) GetReconciliationStatus() string {
	if x != nil {
		return x.ReconciliationStatus
	}
	return ""
}

var File_internal_api_settlement_settlement_proto protoreflect.FileDescriptor

const file_internal_api_settlement_settlement_proto_rawDesc = "" +
	"\n" +
	"(internal/api/settlement/settlement.proto\x12\n" +
	"settlement\"2\n" +
	"\x15ReconcileBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"W\n" +
	"\x16ReconcileBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"2\n" +
	"\x15GetBatchStatusRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"\xaa\x01\n" +
	"\x16GetBatchStatusResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1d\n" +
	"\n" +
	"batch_date\x18\x02 \x01(\tR\tbatchDate\x12!\n" +
	"\fbatch_status\x18\x03 \x01(\tR\vbatchStatus\x123\n" +
	"\x15reconciliation_status\x18\x04 \x01(\tR\x14reconciliationStatus2\xc5\x01\n" +
	"\x11SettlementService\x12W\n" +
	"\x0eReconcileBatch\x12!.settlement.ReconcileBatchRequest\x1a\".settlement.ReconcileBatchResponse\x12W\n" +
	"\x0eGetBatchStatus\x12!.settlement.GetBatchStatusRequest\x1a\".settlement.GetBatchStatusResponseB.Z,cardnet/internal/api/settlement;settlementpbb\x06proto3"

var (
	file_internal_api_settlement_settlement_proto_rawDescOnce sync.Once
	file_internal_api_settlement_settlement_proto_rawDescData []byte
)

func file_internal_api_settlement_settlement_proto_rawDescGZIP() []byte {
	file_internal_api_settlement_settlement_proto_rawDescOnce.Do(func() {
		file_internal_api_settlement_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_settlement_settlement_proto_rawDesc), len(file_internal_api_settlement_settlement_proto_rawDesc)))
	})
	return file_internal_api_settlement_settlement_proto_rawDescData
}

var file_internal_api_settlement_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_settlement_settlement_proto_goTypes = []any{
	(*ReconcileBatchRequest)(nil),  // 0: settlement.ReconcileBatchRequest
	(*ReconcileBatchResponse)(nil), // 1: settlement.ReconcileBatchResponse
	(*GetBatchStatusRequest)(nil),  // 2: settlement.GetBatchStatusRequest
	(*GetBatchStatusResponse)(nil), // 3: settlement.GetBatchStatusResponse
}
var file_internal_api_settlement_settlement_proto_depIdxs = []int32{
	0, // 0: settlement.SettlementService.ReconcileBatch:input_type -> settlement.ReconcileBatchRequest
	2, // 1: settlement.SettlementService.GetBatchStatus:input_type -> settlement.GetBatchStatusRequest
	1, // 2: settlement.SettlementService.ReconcileBatch:output_type -> settlement.ReconcileBatchResponse
	3, // 3: settlement.SettlementService.GetBatchStatus:output_type -> settlement.GetBatchStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_settlement_settlement_proto_init() }
func file_internal_api_settlement_settlement_proto_init() {
	if File_internal_api_settlement_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_settlement_settlement_proto_rawDesc), len(file_internal_api_settlement_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_settlement_settlement_proto_goTypes,
		DependencyIndexes: file_internal_api_settlement_settlement_proto_depIdxs,
		MessageInfos:      file_internal_api_settlement_settlement_proto_msgTypes,
	}.Build()
	File_internal_api_settlement_settlement_proto = out.File
	file_internal_api_settlement_settlement_proto_goTypes = nil
	file_internal_api_settlement_settlement_proto_depIdxs = nil
}
