// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/ledger/ledger.proto

package ledgerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_AUTH_REQUEST           EventType = 1
	EventType_RISK_DECISION          EventType = 2
	EventType_ISSUER_RESPONSE        EventType = 3
	EventType_FINAL_OUTCOME          EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "AUTH_REQUEST",
		2: "RISK_DECISION",
		3: "ISSUER_RESPONSE",
		4: "FINAL_OUTCOME",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"AUTH_REQUEST":           1,
		"RISK_DECISION":          2,
		"ISSUER_RESPONSE":        3,
		"FINAL_OUTCOME":          4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_ledger_ledger_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_internal_api_ledger_ledger_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVED             Decision = 1
	Decision_DECLINED             Decision = 2
	Decision_REVIEW               Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "APPROVED",
		2: "DECLINED",
		3: "REVIEW",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"APPROVED":             1,
		"DECLINED":             2,
		"REVIEW":               3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_ledger_ledger_proto_enumTypes[1].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_internal_api_ledger_ledger_proto_enumTypes[1]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

type AuthEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AuthId        string                 `protobuf:"bytes,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CardHash      string                 `protobuf:"bytes,4,opt,name=card_hash,json=cardHash,proto3" json:"card_hash,omitempty"`
	EventType     EventType              `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=ledger.v1.EventType" json:"event_type,omitempty"`
	Decision      Decision               `protobuf:"varint,6,opt,name=decision,proto3,enum=ledger.v1.Decision" json:"decision,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEvent) Reset() {
	*x = AuthEvent{}
	mi := &file_internal_api_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEvent) ProtoMessage() {}

func (x *AuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEvent.ProtoReflect.Descriptor instead.
func (*AuthEvent) Descriptor() ([]byte, []int) {
	return file_internal_api_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *AuthEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthEvent) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *AuthEvent) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AuthEvent) GetCardHash() string {
	if x != nil {
		return x.CardHash
	}
	return ""
}

func (x *AuthEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AuthEvent) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *AuthEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthEvent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RecordEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEventResponse) Reset() {
	*x = RecordEventResponse{}
	mi := &file_internal_api_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEventResponse) ProtoMessage() {}

func (x *RecordEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEventResponse.ProtoReflect.Descriptor instead.
func (*RecordEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_internal_api_ledger_ledger_proto protoreflect.FileDescriptor

const file_internal_api_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	" internal/api/ledger/ledger.proto\x12\tledger.v1\"\x9c\x02\n" +
	"\tAuthEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\tR\x06authId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\tcard_hash\x18\x04 \x01(\tR\bcardHash\x123\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x14.ledger.v1.EventTypeR\teventType\x12/\n" +
	"\bdecision\x18\x06 \x01(\x0e2\x13.ledger.v1.DecisionR\bdecision\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"1\n" +
	"\x13RecordEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*t\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fAUTH_REQUEST\x10\x01\x12\x11\n" +
	"\rRISK_DECISION\x10\x02\x12\x13\n" +
	"\x0fISSUER_RESPONSE\x10\x03\x12\x11\n" +
	"\rFINAL_OUTCOME\x10\x04*L\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bDECLINED\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x032Y\n" +
	"\x12EventLedgerService\x12C\n" +
	"\vRecordEvent\x12\x14.ledger.v1.AuthEvent\x1a\x1e.ledger.v1.RecordEventResponseB&Z$cardnet/internal/api/ledger;ledgerpbb\x06proto3"

var (
	file_internal_api_ledger_ledger_proto_rawDescOnce sync.Once
	file_internal_api_ledger_ledger_proto_rawDescData []byte
)

func file_internal_api_ledger_ledger_proto_rawDescGZIP() []byte {
	file_internal_api_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_internal_api_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_ledger_ledger_proto_rawDesc), len(file_internal_api_ledger_ledger_proto_rawDesc)))
	})
	return file_internal_api_ledger_ledger_proto_rawDescData
}

var file_internal_api_ledger_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_api_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_ledger_ledger_proto_goTypes = []any{
	(EventType)(0),              // 0: ledger.v1.EventType
	(Decision)(0),               // 1: ledger.v1.Decision
	(*AuthEvent)(nil),           // 2: ledger.v1.AuthEvent
	(*RecordEventResponse)(nil), // 3: ledger.v1.RecordEventResponse
}
var file_internal_api_ledger_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.v1.AuthEvent.event_type:type_name -> ledger.v1.EventType
	1, // 1: ledger.v1.AuthEvent.decision:type_name -> ledger.v1.Decision
	2, // 2: ledger.v1.EventLedgerService.RecordEvent:input_type -> ledger.v1.AuthEvent
	3, // 3: ledger.v1.EventLedgerService.RecordEvent:output_type -> ledger.v1.RecordEventResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_ledger_ledger_proto_init() }
func file_internal_api_ledger_ledger_proto_init() {
	if File_internal_api_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_ledger_ledger_proto_rawDesc), len(file_internal_api_ledger_ledger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_internal_api_ledger_ledger_proto_depIdxs,
		EnumInfos:         file_internal_api_ledger_ledger_proto_enumTypes,
		MessageInfos:      file_internal_api_ledger_ledger_proto_msgTypes,
	}.Build()
	File_internal_api_ledger_ledger_proto = out.File
	file_internal_api_ledger_ledger_proto_goTypes = nil
	file_internal_api_ledger_ledger_proto_depIdxs = nil
}
