// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/api/ledger/ledger.proto

package ledgerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventLedgerService_RecordEvent_FullMethodName = "/ledger.v1.EventLedgerService/RecordEvent"
)

// EventLedgerServiceClient is the client API for EventLedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventLedgerServiceClient interface {
	RecordEvent(ctx context.Context, in *AuthEvent, opts ...grpc.CallOption) (*RecordEventResponse, error)
}

type eventLedgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventLedgerServiceClient(cc grpc.ClientConnInterface) EventLedgerServiceClient {
	return &eventLedgerServiceClient{cc}
}

func (c *eventLedgerServiceClient) RecordEvent(ctx context.Context, in *AuthEvent, opts ...grpc.CallOption) (*RecordEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEventResponse)
	err := c.cc.Invoke(ctx, EventLedgerService_RecordEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventLedgerServiceServer is the server API for EventLedgerService service.
// All implementations must embed UnimplementedEventLedgerServiceServer
// for forward compatibility.
type EventLedgerServiceServer interface {
	RecordEvent(context.Context, *AuthEvent) (*RecordEventResponse, error)
	mustEmbedUnimplementedEventLedgerServiceServer()
}

// UnimplementedEventLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventLedgerServiceServer struct{}

func (UnimplementedEventLedgerServiceServer) RecordEvent(context.Context, *AuthEvent) (*RecordEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEvent not implemented")
}
func (UnimplementedEventLedgerServiceServer) mustEmbedUnimplementedEventLedgerServiceServer() {}
func (UnimplementedEventLedgerServiceServer) testEmbeddedByValue()                            {}

// UnsafeEventLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventLedgerServiceServer will
// result in compilation errors.
type UnsafeEventLedgerServiceServer interface {
	mustEmbedUnimplementedEventLedgerServiceServer()
}

func RegisterEventLedgerServiceServer(s grpc.ServiceRegistrar, srv EventLedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedEventLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventLedgerService_ServiceDesc, srv)
}

func _EventLedgerService_RecordEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventLedgerServiceServer).RecordEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventLedgerService_RecordEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventLedgerServiceServer).RecordEvent(ctx, req.(*AuthEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// EventLedgerService_ServiceDesc is the grpc.ServiceDesc for EventLedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventLedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.v1.EventLedgerService",
	HandlerType: (*EventLedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEvent",
			Handler:    _EventLedgerService_RecordEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/ledger/ledger.proto",
}
