// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/risk/risk.proto

package riskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================
// Enums
// ==========================
type Decision int32

const (
	Decision_DECISION_UNSPECIFIED Decision = 0
	Decision_APPROVE              Decision = 1
	Decision_SOFT_DECLINE         Decision = 2
	Decision_HARD_DECLINE         Decision = 3
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "APPROVE",
		2: "SOFT_DECLINE",
		3: "HARD_DECLINE",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"APPROVE":              1,
		"SOFT_DECLINE":         2,
		"HARD_DECLINE":         3,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_risk_risk_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_internal_api_risk_risk_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_risk_risk_proto_rawDescGZIP(), []int{0}
}

// ==========================
// Requests
// ==========================
type RiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Context       *RiskContext           `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
	mi := &file_internal_api_risk_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_risk_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRequest.ProtoReflect.Descriptor instead.
func (*RiskRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_risk_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *RiskRequest) GetContext() *RiskContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// Core transaction info (from auth)
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Bin           string                 `protobuf:"bytes,3,opt,name=bin,proto3" json:"bin,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Mcc           string                 `protobuf:"bytes,6,opt,name=mcc,proto3" json:"mcc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_api_risk_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_risk_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_api_risk_risk_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Transaction) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *Transaction) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

// Optional context (extensible, Phase 4+)
type RiskContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Velocity
	TxCount_1M int32 `protobuf:"varint,1,opt,name=tx_count_1m,json=txCount1m,proto3" json:"tx_count_1m,omitempty"`
	TxCount_5M int32 `protobuf:"varint,2,opt,name=tx_count_5m,json=txCount5m,proto3" json:"tx_count_5m,omitempty"`
	// Geo
	LastCountry string `protobuf:"bytes,3,opt,name=last_country,json=lastCountry,proto3" json:"last_country,omitempty"`
	LastTxTs    int64  `protobuf:"varint,4,opt,name=last_tx_ts,json=lastTxTs,proto3" json:"last_tx_ts,omitempty"`
	// Amount profile
	AvgAmount int64 `protobuf:"varint,5,opt,name=avg_amount,json=avgAmount,proto3" json:"avg_amount,omitempty"`
	P95Amount int64 `protobuf:"varint,6,opt,name=p95_amount,json=p95Amount,proto3" json:"p95_amount,omitempty"`
	// External scores
	MerchantRiskScore int32 `protobuf:"varint,7,opt,name=merchant_risk_score,json=merchantRiskScore,proto3" json:"merchant_risk_score,omitempty"`
	BinRiskScore      int32 `protobuf:"varint,8,opt,name=bin_risk_score,json=binRiskScore,proto3" json:"bin_risk_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RiskContext) Reset() {
	*x = RiskContext{}
	mi := &file_internal_api_risk_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskContext) ProtoMessage() {}

func (x *RiskContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_risk_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskContext.ProtoReflect.Descriptor instead.
func (*RiskContext) Descriptor() ([]byte, []int) {
	return file_internal_api_risk_risk_proto_rawDescGZIP(), []int{2}
}

func (x *RiskContext) GetTxCount_1M() int32 {
	if x != nil {
		return x.TxCount_1M
	}
	return 0
}

func (x *RiskContext) GetTxCount_5M() int32 {
	if x != nil {
		return x.TxCount_5M
	}
	return 0
}

func (x *RiskContext) GetLastCountry() string {
	if x != nil {
		return x.LastCountry
	}
	return ""
}

func (x *RiskContext) GetLastTxTs() int64 {
	if x != nil {
		return x.LastTxTs
	}
	return 0
}

func (x *RiskContext) GetAvgAmount() int64 {
	if x != nil {
		return x.AvgAmount
	}
	return 0
}

func (x *RiskContext) GetP95Amount() int64 {
	if x != nil {
		return x.P95Amount
	}
	return 0
}

func (x *RiskContext) GetMerchantRiskScore() int32 {
	if x != nil {
		return x.MerchantRiskScore
	}
	return 0
}

func (x *RiskContext) GetBinRiskScore() int32 {
	if x != nil {
		return x.BinRiskScore
	}
	return 0
}

// ==========================
// Responses
// ==========================
type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=risk.Decision" json:"decision,omitempty"`
	RiskScore     int32                  `protobuf:"varint,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Reasons       []string               `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_internal_api_risk_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_risk_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_risk_risk_proto_rawDescGZIP(), []int{3}
}

func (x *RiskResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *RiskResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

var File_internal_api_risk_risk_proto protoreflect.FileDescriptor

const file_internal_api_risk_risk_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/api/risk/risk.proto\x12\x04risk\"o\n" +
	"\vRiskRequest\x123\n" +
	"\vtransaction\x18\x01 \x01(\v2\x11.risk.TransactionR\vtransaction\x12+\n" +
	"\acontext\x18\x02 \x01(\v2\x11.risk.RiskContextR\acontext\"\xa5\x01\n" +
	"\vTransaction\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x10\n" +
	"\x03bin\x18\x03 \x01(\tR\x03bin\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03mcc\x18\x06 \x01(\tR\x03mcc\"\xa2\x02\n" +
	"\vRiskContext\x12\x1e\n" +
	"\vtx_count_1m\x18\x01 \x01(\x05R\ttxCount1m\x12\x1e\n" +
	"\vtx_count_5m\x18\x02 \x01(\x05R\ttxCount5m\x12!\n" +
	"\flast_country\x18\x03 \x01(\tR\vlastCountry\x12\x1c\n" +
	"\n" +
	"last_tx_ts\x18\x04 \x01(\x03R\blastTxTs\x12\x1d\n" +
	"\n" +
	"avg_amount\x18\x05 \x01(\x03R\tavgAmount\x12\x1d\n" +
	"\n" +
	"p95_amount\x18\x06 \x01(\x03R\tp95Amount\x12.\n" +
	"\x13merchant_risk_score\x18\a \x01(\x05R\x11merchantRiskScore\x12$\n" +
	"\x0ebin_risk_score\x18\b \x01(\x05R\fbinRiskScore\"s\n" +
	"\fRiskResponse\x12*\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x0e.risk.DecisionR\bdecision\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x05R\triskScore\x12\x18\n" +
	"\areasons\x18\x03 \x03(\tR\areasons*U\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPROVE\x10\x01\x12\x10\n" +
	"\fSOFT_DECLINE\x10\x02\x12\x10\n" +
	"\fHARD_DECLINE\x10\x032?\n" +
	"\n" +
	"RiskEngine\x121\n" +
	"\bEvaluate\x12\x11.risk.RiskRequest\x1a\x12.risk.RiskResponseB\"Z cardnet/internal/api/risk;riskpbb\x06proto3"

var (
	file_internal_api_risk_risk_proto_rawDescOnce sync.Once
	file_internal_api_risk_risk_proto_rawDescData []byte
)

func file_internal_api_risk_risk_proto_rawDescGZIP() []byte {
	file_internal_api_risk_risk_proto_rawDescOnce.Do(func() {
		file_internal_api_risk_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_risk_risk_proto_rawDesc), len(file_internal_api_risk_risk_proto_rawDesc)))
	})
	return file_internal_api_risk_risk_proto_rawDescData
}

var file_internal_api_risk_risk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_api_risk_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_risk_risk_proto_goTypes = []any{
	(Decision)(0),        // 0: risk.Decision
	(*RiskRequest)(nil),  // 1: risk.RiskRequest
	(*Transaction)(nil),  // 2: risk.Transaction
	(*RiskContext)(nil),  // 3: risk.RiskContext
	(*RiskResponse)(nil), // 4: risk.RiskResponse
}
var file_internal_api_risk_risk_proto_depIdxs = []int32{
	2, // 0: risk.RiskRequest.transaction:type_name -> risk.Transaction
	3, // 1: risk.RiskRequest.context:type_name -> risk.RiskContext
	0, // 2: risk.RiskResponse.decision:type_name -> risk.Decision
	1, // 3: risk.RiskEngine.Evaluate:input_type -> risk.RiskRequest
	4, // 4: risk.RiskEngine.Evaluate:output_type -> risk.RiskResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_api_risk_risk_proto_init() }
func file_internal_api_risk_risk_proto_init() {
	if File_internal_api_risk_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_risk_risk_proto_rawDesc), len(file_internal_api_risk_risk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_risk_risk_proto_goTypes,
		DependencyIndexes: file_internal_api_risk_risk_proto_depIdxs,
		EnumInfos:         file_internal_api_risk_risk_proto_enumTypes,
		MessageInfos:      file_internal_api_risk_risk_proto_msgTypes,
	}.Build()
	File_internal_api_risk_risk_proto = out.File
	file_internal_api_risk_risk_proto_goTypes = nil
	file_internal_api_risk_risk_proto_depIdxs = nil
}
