// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMerchantStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantStatsRequest) Reset() {
	*x = GetMerchantStatsRequest{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantStatsRequest) ProtoMessage() {}

func (x *GetMerchantStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetMerchantStatsRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type GetMerchantStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TxCount       int64                  `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	ApprovedTx    int64                  `protobuf:"varint,3,opt,name=approved_tx,json=approvedTx,proto3" json:"approved_tx,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ApprovalRate  float64                `protobuf:"fixed64,5,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantStatsResponse) Reset() {
	*x = GetMerchantStatsResponse{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantStatsResponse) ProtoMessage() {}

func (x *GetMerchantStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetMerchantStatsResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetMerchantStatsResponse) GetTxCount() int64 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *GetMerchantStatsResponse) GetApprovedTx() int64 {
	if x != nil {
		return x.ApprovedTx
	}
	return 0
}

func (x *GetMerchantStatsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetMerchantStatsResponse) GetApprovalRate() float64 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

type GetBinStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bin           string                 `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinStatsRequest) Reset() {
	*x = GetBinStatsRequest{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinStatsRequest) ProtoMessage() {}

func (x *GetBinStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBinStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetBinStatsRequest) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

type GetBinStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bin           string                 `protobuf:"bytes,1,opt,name=bin,proto3" json:"bin,omitempty"`
	TxCount       int64                  `protobuf:"varint,2,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	ApprovedTx    int64                  `protobuf:"varint,3,opt,name=approved_tx,json=approvedTx,proto3" json:"approved_tx,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ApprovalRate  float64                `protobuf:"fixed64,5,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinStatsResponse) Reset() {
	*x = GetBinStatsResponse{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinStatsResponse) ProtoMessage() {}

func (x *GetBinStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBinStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetBinStatsResponse) GetBin() string {
	if x != nil {
		return x.Bin
	}
	return ""
}

func (x *GetBinStatsResponse) GetTxCount() int64 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *GetBinStatsResponse) GetApprovedTx() int64 {
	if x != nil {
		return x.ApprovedTx
	}
	return 0
}

func (x *GetBinStatsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetBinStatsResponse) GetApprovalRate() float64 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

type GetRuleEffectivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleEffectivenessRequest) Reset() {
	*x = GetRuleEffectivenessRequest{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleEffectivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleEffectivenessRequest) ProtoMessage() {}

func (x *GetRuleEffectivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleEffectivenessRequest.ProtoReflect.Descriptor instead.
func (*GetRuleEffectivenessRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetRuleEffectivenessRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type GetRuleEffectivenessResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RuleId         string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	TriggeredCount int64                  `protobuf:"varint,2,opt,name=triggered_count,json=triggeredCount,proto3" json:"triggered_count,omitempty"`
	DeclineCount   int64                  `protobuf:"varint,3,opt,name=decline_count,json=declineCount,proto3" json:"decline_count,omitempty"`
	DeclineRate    float64                `protobuf:"fixed64,4,opt,name=decline_rate,json=declineRate,proto3" json:"decline_rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRuleEffectivenessResponse) Reset() {
	*x = GetRuleEffectivenessResponse{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleEffectivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleEffectivenessResponse) ProtoMessage() {}

func (x *GetRuleEffectivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleEffectivenessResponse.ProtoReflect.Descriptor instead.
func (*GetRuleEffectivenessResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetRuleEffectivenessResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GetRuleEffectivenessResponse) GetTriggeredCount() int64 {
	if x != nil {
		return x.TriggeredCount
	}
	return 0
}

func (x *GetRuleEffectivenessResponse) GetDeclineCount() int64 {
	if x != nil {
		return x.DeclineCount
	}
	return 0
}

func (x *GetRuleEffectivenessResponse) GetDeclineRate() float64 {
	if x != nil {
		return x.DeclineRate
	}
	return 0
}

type GetNetworkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsRequest) Reset() {
	*x = GetNetworkStatsRequest{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsRequest) ProtoMessage() {}

func (x *GetNetworkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

type GetNetworkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTx       int64                  `protobuf:"varint,1,opt,name=total_tx,json=totalTx,proto3" json:"total_tx,omitempty"`
	ApprovedTx    int64                  `protobuf:"varint,2,opt,name=approved_tx,json=approvedTx,proto3" json:"approved_tx,omitempty"`
	ApprovalRate  float64                `protobuf:"fixed64,3,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkStatsResponse) Reset() {
	*x = GetNetworkStatsResponse{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkStatsResponse) ProtoMessage() {}

func (x *GetNetworkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkStatsResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetNetworkStatsResponse) GetTotalTx() int64 {
	if x != nil {
		return x.TotalTx
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetApprovedTx() int64 {
	if x != nil {
		return x.ApprovedTx
	}
	return 0
}

func (x *GetNetworkStatsResponse) GetApprovalRate() float64 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

// Network-wide transaction history
type NetworkHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkHistoryItem) Reset() {
	*x = NetworkHistoryItem{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkHistoryItem) ProtoMessage() {}

func (x *NetworkHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkHistoryItem.ProtoReflect.Descriptor instead.
func (*NetworkHistoryItem) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkHistoryItem) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *NetworkHistoryItem) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *NetworkHistoryItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NetworkHistoryItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *NetworkHistoryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NetworkHistoryItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NetworkHistoryItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetNetworkHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	MerchantId    string `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkHistoryRequest) Reset() {
	*x = GetNetworkHistoryRequest{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkHistoryRequest) ProtoMessage() {}

func (x *GetNetworkHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkHistoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetNetworkHistoryRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetNetworkHistoryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetNetworkHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNetworkHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NetworkHistoryItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkHistoryResponse) Reset() {
	*x = GetNetworkHistoryResponse{}
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkHistoryResponse) ProtoMessage() {}

func (x *GetNetworkHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkHistoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetNetworkHistoryResponse) GetItems() []*NetworkHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_api_analytics_analytics_proto protoreflect.FileDescriptor

const file_internal_api_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"&internal/api/analytics/analytics.proto\x12\tanalytics\":\n" +
	"\x17GetMerchantStatsRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\xbf\x01\n" +
	"\x18GetMerchantStatsResponse\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x03R\atxCount\x12\x1f\n" +
	"\vapproved_tx\x18\x03 \x01(\x03R\n" +
	"approvedTx\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12#\n" +
	"\rapproval_rate\x18\x05 \x01(\x01R\fapprovalRate\"&\n" +
	"\x12GetBinStatsRequest\x12\x10\n" +
	"\x03bin\x18\x01 \x01(\tR\x03bin\"\xab\x01\n" +
	"\x13GetBinStatsResponse\x12\x10\n" +
	"\x03bin\x18\x01 \x01(\tR\x03bin\x12\x19\n" +
	"\btx_count\x18\x02 \x01(\x03R\atxCount\x12\x1f\n" +
	"\vapproved_tx\x18\x03 \x01(\x03R\n" +
	"approvedTx\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12#\n" +
	"\rapproval_rate\x18\x05 \x01(\x01R\fapprovalRate\"6\n" +
	"\x1bGetRuleEffectivenessRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\"\xa8\x01\n" +
	"\x1cGetRuleEffectivenessResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12'\n" +
	"\x0ftriggered_count\x18\x02 \x01(\x03R\x0etriggeredCount\x12#\n" +
	"\rdecline_count\x18\x03 \x01(\x03R\fdeclineCount\x12!\n" +
	"\fdecline_rate\x18\x04 \x01(\x01R\vdeclineRate\"\x18\n" +
	"\x16GetNetworkStatsRequest\"z\n" +
	"\x17GetNetworkStatsResponse\x12\x19\n" +
	"\btotal_tx\x18\x01 \x01(\x03R\atotalTx\x12\x1f\n" +
	"\vapproved_tx\x18\x02 \x01(\x03R\n" +
	"approvedTx\x12#\n" +
	"\rapproval_rate\x18\x03 \x01(\x01R\fapprovalRate\"\xd1\x01\n" +
	"\x12NetworkHistoryItem\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"i\n" +
	"\x18GetNetworkHistoryRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"P\n" +
	"\x19GetNetworkHistoryResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.analytics.NetworkHistoryItemR\x05items2\xe0\x03\n" +
	"\x10AnalyticsService\x12[\n" +
	"\x10GetMerchantStats\x12\".analytics.GetMerchantStatsRequest\x1a#.analytics.GetMerchantStatsResponse\x12L\n" +
	"\vGetBinStats\x12\x1d.analytics.GetBinStatsRequest\x1a\x1e.analytics.GetBinStatsResponse\x12g\n" +
	"\x14GetRuleEffectiveness\x12&.analytics.GetRuleEffectivenessRequest\x1a'.analytics.GetRuleEffectivenessResponse\x12X\n" +
	"\x0fGetNetworkStats\x12!.analytics.GetNetworkStatsRequest\x1a\".analytics.GetNetworkStatsResponse\x12^\n" +
	"\x11GetNetworkHistory\x12#.analytics.GetNetworkHistoryRequest\x1a$.analytics.GetNetworkHistoryResponseB Z\x1ecardnet/internal/api/analyticsb\x06proto3"

var (
	file_internal_api_analytics_analytics_proto_rawDescOnce sync.Once
	file_internal_api_analytics_analytics_proto_rawDescData []byte
)

func file_internal_api_analytics_analytics_proto_rawDescGZIP() []byte {
	file_internal_api_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_internal_api_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_analytics_analytics_proto_rawDesc), len(file_internal_api_analytics_analytics_proto_rawDesc)))
	})
	return file_internal_api_analytics_analytics_proto_rawDescData
}

var file_internal_api_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_api_analytics_analytics_proto_goTypes = []any{
	(*GetMerchantStatsRequest)(nil),      // 0: analytics.GetMerchantStatsRequest
	(*GetMerchantStatsResponse)(nil),     // 1: analytics.GetMerchantStatsResponse
	(*GetBinStatsRequest)(nil),           // 2: analytics.GetBinStatsRequest
	(*GetBinStatsResponse)(nil),          // 3: analytics.GetBinStatsResponse
	(*GetRuleEffectivenessRequest)(nil),  // 4: analytics.GetRuleEffectivenessRequest
	(*GetRuleEffectivenessResponse)(nil), // 5: analytics.GetRuleEffectivenessResponse
	(*GetNetworkStatsRequest)(nil),       // 6: analytics.GetNetworkStatsRequest
	(*GetNetworkStatsResponse)(nil),      // 7: analytics.GetNetworkStatsResponse
	(*NetworkHistoryItem)(nil),           // 8: analytics.NetworkHistoryItem
	(*GetNetworkHistoryRequest)(nil),     // 9: analytics.GetNetworkHistoryRequest
	(*GetNetworkHistoryResponse)(nil),    // 10: analytics.GetNetworkHistoryResponse
}
var file_internal_api_analytics_analytics_proto_depIdxs = []int32{
	8,  // 0: analytics.GetNetworkHistoryResponse.items:type_name -> analytics.NetworkHistoryItem
	0,  // 1: analytics.AnalyticsService.GetMerchantStats:input_type -> analytics.GetMerchantStatsRequest
	2,  // 2: analytics.AnalyticsService.GetBinStats:input_type -> analytics.GetBinStatsRequest
	4,  // 3: analytics.AnalyticsService.GetRuleEffectiveness:input_type -> analytics.GetRuleEffectivenessRequest
	6,  // 4: analytics.AnalyticsService.GetNetworkStats:input_type -> analytics.GetNetworkStatsRequest
	9,  // 5: analytics.AnalyticsService.GetNetworkHistory:input_type -> analytics.GetNetworkHistoryRequest
	1,  // 6: analytics.AnalyticsService.GetMerchantStats:output_type -> analytics.GetMerchantStatsResponse
	3,  // 7: analytics.AnalyticsService.GetBinStats:output_type -> analytics.GetBinStatsResponse
	5,  // 8: analytics.AnalyticsService.GetRuleEffectiveness:output_type -> analytics.GetRuleEffectivenessResponse
	7,  // 9: analytics.AnalyticsService.GetNetworkStats:output_type -> analytics.GetNetworkStatsResponse
	10, // 10: analytics.AnalyticsService.GetNetworkHistory:output_type -> analytics.GetNetworkHistoryResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_analytics_analytics_proto_init() }
func file_internal_api_analytics_analytics_proto_init() {
	if File_internal_api_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_analytics_analytics_proto_rawDesc), len(file_internal_api_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_internal_api_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_internal_api_analytics_analytics_proto_msgTypes,
	}.Build()
	File_internal_api_analytics_analytics_proto = out.File
	file_internal_api_analytics_analytics_proto_goTypes = nil
	file_internal_api_analytics_analytics_proto_depIdxs = nil
}
