// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: internal/api/analytics/analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetMerchantStats_FullMethodName     = "/analytics.AnalyticsService/GetMerchantStats"
	AnalyticsService_GetBinStats_FullMethodName          = "/analytics.AnalyticsService/GetBinStats"
	AnalyticsService_GetRuleEffectiveness_FullMethodName = "/analytics.AnalyticsService/GetRuleEffectiveness"
	AnalyticsService_GetNetworkStats_FullMethodName      = "/analytics.AnalyticsService/GetNetworkStats"
	AnalyticsService_GetNetworkHistory_FullMethodName    = "/analytics.AnalyticsService/GetNetworkHistory"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetMerchantStats(ctx context.Context, in *GetMerchantStatsRequest, opts ...grpc.CallOption) (*GetMerchantStatsResponse, error)
	GetBinStats(ctx context.Context, in *GetBinStatsRequest, opts ...grpc.CallOption) (*GetBinStatsResponse, error)
	GetRuleEffectiveness(ctx context.Context, in *GetRuleEffectivenessRequest, opts ...grpc.CallOption) (*GetRuleEffectivenessResponse, error)
	GetNetworkStats(ctx context.Context, in *GetNetworkStatsRequest, opts ...grpc.CallOption) (*GetNetworkStatsResponse, error)
	// Network-wide authorization history across merchants
	GetNetworkHistory(ctx context.Context, in *GetNetworkHistoryRequest, opts ...grpc.CallOption) (*GetNetworkHistoryResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetMerchantStats(ctx context.Context, in *GetMerchantStatsRequest, opts ...grpc.CallOption) (*GetMerchantStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMerchantStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetMerchantStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetBinStats(ctx context.Context, in *GetBinStatsRequest, opts ...grpc.CallOption) (*GetBinStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBinStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetBinStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRuleEffectiveness(ctx context.Context, in *GetRuleEffectivenessRequest, opts ...grpc.CallOption) (*GetRuleEffectivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleEffectivenessResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetRuleEffectiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetNetworkStats(ctx context.Context, in *GetNetworkStatsRequest, opts ...grpc.CallOption) (*GetNetworkStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetNetworkStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetNetworkHistory(ctx context.Context, in *GetNetworkHistoryRequest, opts ...grpc.CallOption) (*GetNetworkHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkHistoryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetNetworkHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetMerchantStats(context.Context, *GetMerchantStatsRequest) (*GetMerchantStatsResponse, error)
	GetBinStats(context.Context, *GetBinStatsRequest) (*GetBinStatsResponse, error)
	GetRuleEffectiveness(context.Context, *GetRuleEffectivenessRequest) (*GetRuleEffectivenessResponse, error)
	GetNetworkStats(context.Context, *GetNetworkStatsRequest) (*GetNetworkStatsResponse, error)
	// Network-wide authorization history across merchants
	GetNetworkHistory(context.Context, *GetNetworkHistoryRequest) (*GetNetworkHistoryResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetMerchantStats(context.Context, *GetMerchantStatsRequest) (*GetMerchantStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMerchantStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetBinStats(context.Context, *GetBinStatsRequest) (*GetBinStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRuleEffectiveness(context.Context, *GetRuleEffectivenessRequest) (*GetRuleEffectivenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleEffectiveness not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetNetworkStats(context.Context, *GetNetworkStatsRequest) (*GetNetworkStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetNetworkHistory(context.Context, *GetNetworkHistoryRequest) (*GetNetworkHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkHistory not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetMerchantStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMerchantStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetMerchantStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetMerchantStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetMerchantStats(ctx, req.(*GetMerchantStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetBinStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetBinStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetBinStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetBinStats(ctx, req.(*GetBinStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRuleEffectiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleEffectivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetRuleEffectiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetRuleEffectiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetRuleEffectiveness(ctx, req.(*GetRuleEffectivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetNetworkStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetNetworkStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetNetworkStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetNetworkStats(ctx, req.(*GetNetworkStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetNetworkHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetNetworkHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetNetworkHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetNetworkHistory(ctx, req.(*GetNetworkHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMerchantStats",
			Handler:    _AnalyticsService_GetMerchantStats_Handler,
		},
		{
			MethodName: "GetBinStats",
			Handler:    _AnalyticsService_GetBinStats_Handler,
		},
		{
			MethodName: "GetRuleEffectiveness",
			Handler:    _AnalyticsService_GetRuleEffectiveness_Handler,
		},
		{
			MethodName: "GetNetworkStats",
			Handler:    _AnalyticsService_GetNetworkStats_Handler,
		},
		{
			MethodName: "GetNetworkHistory",
			Handler:    _AnalyticsService_GetNetworkHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/analytics/analytics.proto",
}
