// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/grpc/auth.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CardToken     string                 `protobuf:"bytes,3,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Mcc           string                 `protobuf:"bytes,6,opt,name=mcc,proto3" json:"mcc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_internal_api_grpc_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuthRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AuthRequest) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *AuthRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthRequest) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_internal_api_grpc_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *AuthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_api_grpc_auth_proto protoreflect.FileDescriptor

const file_internal_api_grpc_auth_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/api/grpc/auth.proto\x12\x04auth\"\xb2\x01\n" +
	"\vAuthRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\tR\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"card_token\x18\x03 \x01(\tR\tcardToken\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x10\n" +
	"\x03mcc\x18\x06 \x01(\tR\x03mcc\"?\n" +
	"\fAuthResponse\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2A\n" +
	"\vAuthGateway\x122\n" +
	"\tAuthorize\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponseB Z\x1ecardnet/internal/api/grpc;grpcb\x06proto3"

var (
	file_internal_api_grpc_auth_proto_rawDescOnce sync.Once
	file_internal_api_grpc_auth_proto_rawDescData []byte
)

func file_internal_api_grpc_auth_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_auth_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_auth_proto_rawDesc), len(file_internal_api_grpc_auth_proto_rawDesc)))
	})
	return file_internal_api_grpc_auth_proto_rawDescData
}

var file_internal_api_grpc_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_grpc_auth_proto_goTypes = []any{
	(*AuthRequest)(nil),  // 0: auth.AuthRequest
	(*AuthResponse)(nil), // 1: auth.AuthResponse
}
var file_internal_api_grpc_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthGateway.Authorize:input_type -> auth.AuthRequest
	1, // 1: auth.AuthGateway.Authorize:output_type -> auth.AuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_auth_proto_init() }
func file_internal_api_grpc_auth_proto_init() {
	if File_internal_api_grpc_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_auth_proto_rawDesc), len(file_internal_api_grpc_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_auth_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_auth_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_auth_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_auth_proto = out.File
	file_internal_api_grpc_auth_proto_goTypes = nil
	file_internal_api_grpc_auth_proto_depIdxs = nil
}
