// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/api/issuer/issuer.proto

package issuerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssuerAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        string                 `protobuf:"bytes,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerAuthRequest) Reset() {
	*x = IssuerAuthRequest{}
	mi := &file_internal_api_issuer_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerAuthRequest) ProtoMessage() {}

func (x *IssuerAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_issuer_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerAuthRequest.ProtoReflect.Descriptor instead.
func (*IssuerAuthRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_issuer_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *IssuerAuthRequest) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *IssuerAuthRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *IssuerAuthRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *IssuerAuthRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type IssuerAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	DeclineCode   string                 `protobuf:"bytes,2,opt,name=decline_code,json=declineCode,proto3" json:"decline_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerAuthResponse) Reset() {
	*x = IssuerAuthResponse{}
	mi := &file_internal_api_issuer_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerAuthResponse) ProtoMessage() {}

func (x *IssuerAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_issuer_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerAuthResponse.ProtoReflect.Descriptor instead.
func (*IssuerAuthResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_issuer_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *IssuerAuthResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *IssuerAuthResponse) GetDeclineCode() string {
	if x != nil {
		return x.DeclineCode
	}
	return ""
}

var File_internal_api_issuer_issuer_proto protoreflect.FileDescriptor

const file_internal_api_issuer_issuer_proto_rawDesc = "" +
	"\n" +
	" internal/api/issuer/issuer.proto\x12\x06issuer\"\x81\x01\n" +
	"\x11IssuerAuthRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\tR\x06authId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"S\n" +
	"\x12IssuerAuthResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12!\n" +
	"\fdecline_code\x18\x02 \x01(\tR\vdeclineCode2S\n" +
	"\rIssuerService\x12B\n" +
	"\tAuthorize\x12\x19.issuer.IssuerAuthRequest\x1a\x1a.issuer.IssuerAuthResponseB&Z$cardnet/internal/api/issuer;issuerpbb\x06proto3"

var (
	file_internal_api_issuer_issuer_proto_rawDescOnce sync.Once
	file_internal_api_issuer_issuer_proto_rawDescData []byte
)

func file_internal_api_issuer_issuer_proto_rawDescGZIP() []byte {
	file_internal_api_issuer_issuer_proto_rawDescOnce.Do(func() {
		file_internal_api_issuer_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_issuer_issuer_proto_rawDesc), len(file_internal_api_issuer_issuer_proto_rawDesc)))
	})
	return file_internal_api_issuer_issuer_proto_rawDescData
}

var file_internal_api_issuer_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_api_issuer_issuer_proto_goTypes = []any{
	(*IssuerAuthRequest)(nil),  // 0: issuer.IssuerAuthRequest
	(*IssuerAuthResponse)(nil), // 1: issuer.IssuerAuthResponse
}
var file_internal_api_issuer_issuer_proto_depIdxs = []int32{
	0, // 0: issuer.IssuerService.Authorize:input_type -> issuer.IssuerAuthRequest
	1, // 1: issuer.IssuerService.Authorize:output_type -> issuer.IssuerAuthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_issuer_issuer_proto_init() }
func file_internal_api_issuer_issuer_proto_init() {
	if File_internal_api_issuer_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_issuer_issuer_proto_rawDesc), len(file_internal_api_issuer_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_issuer_issuer_proto_goTypes,
		DependencyIndexes: file_internal_api_issuer_issuer_proto_depIdxs,
		MessageInfos:      file_internal_api_issuer_issuer_proto_msgTypes,
	}.Build()
	File_internal_api_issuer_issuer_proto = out.File
	file_internal_api_issuer_issuer_proto_goTypes = nil
	file_internal_api_issuer_issuer_proto_depIdxs = nil
}
